### ISSUE TITLE
Faire une doc propre pour l'env de dev (webhook tout ça tout ça)

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/ForVoyez#121]
Pour que je puisse faire la page d'usage, il faut que je fasse des tests avec
il faudrait faire un petit bout de doc clé en main facile à utiliser & à installer pour avoir tout l'environnement pour faire des tests etc 

Je voudrais pouvoir tout tester côté usage et suscription pour finir le design de la page de design normalement :d

**Comment by LightInn** [comment]
oué
