### ISSUE TITLE
check all user actions security (open parameters) 

### ISSUE THREAD

**Issue by LightInn** [For-Hives/ForVoyez#167]
check user actions security

(il faut pas oublier que les serveur actions reste des endpoint que n'importe qui peut taper :/ si tu veux plus de detail tu peux regarder : https://nextjs.org/blog/security-nextjs-server-components-actions#closures , il proposes des methodes pour augmente la securité avec du chiffrement tournant, mais ca rend juste la tache plus difficile, au finale ca reste des endpoint ouvert )

_Originally posted by @LightInn in https://github.com/For-Hives/ForVoyez/pull/162#discussion_r1611974227_

**Comment by CinquinAndy** [comment]
Tu penses qu'on a des trucs qui vont pas encore là ?

**Comment by LightInn** [comment]
> Tu penses qu'on a des trucs qui vont pas encore là ? 

J'avais mis l'issue pour me rappeler de checké, et du coup;
J'ai tout check, j'ai rien a signaler ^•^
