### ISSUE TITLE
Navigations en doublons ? 

### ISSUE THREAD

**Issue by LightInn** [For-Hives/ForVoyez#169]
Je ne sais pas se que tu en pense, mais je trouve personnellement que la navigations est en doublons, je n'utilise que la barre lateral (car plus proheminante et facile a utiliser, moins loin du centre de l'encran et dans le sens de lecture), et je trouve que la barre en haut pose deux problematique : 

- il n'y a pas de bouton lateral pour revenir a l'ecran d'acceuil du dashboard
- les autres elements sont en doublon 

![image](https://github.com/For-Hives/ForVoyez/assets/28759336/181e3ca2-ee03-44af-b16d-b45acd7bedf4)

**Comment by CinquinAndy** [comment]
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/e8a0feed-767a-4f84-9d7f-2cd710d97489)

effectivement je préfère

**Comment by CinquinAndy** [comment]
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/4fbfdac7-d93c-4322-9db2-1f94e21d219d)
