### ISSUE TITLE
Playgound error response not helpfull

### ISSUE THREAD

**Issue by LightInn** [For-Hives/ForVoyez#170]
Lorsque qu'un nouvel utilisateur arrive sur la plateforme, la permiere chose qu'il vas essayer de faire, c'est d'utiliser le playground pour voir si il peux essayer avant d'acheter (en mode credit gratuit) 

et la c'est le drame..... Si l'utilisateur n'a pas de credit, le playground lache une vielle erreur on dirait que c'est un bug 

![image](https://github.com/For-Hives/ForVoyez/assets/28759336/9766711b-6bb0-4ff7-8335-8ff6991b8fa6)

**Comment by CinquinAndy** [comment]
Alors, effectivement, le mieux ça serait de grisé le bouton avec un tooltip qui dit qu'on a besoin de crédit pour pouvoir utiliser la fonctionnalité ?

**Comment by CinquinAndy** [comment]
j'ia gérer ça comme ça : 
""


![Image](https://github.com/For-Hives/ForVoyez/assets/55706543/82573e79-6de1-425c-9ecc-9106948752b9)


""

**Comment by LightInn** [comment]
Ça me semble pas mal 👍
