### ISSUE TITLE
unused back fuctions ?

### ISSUE THREAD

**Issue by LightInn** [For-Hives/ForVoyez#172]
c'est fonctions semble ne plus etres utilisé : 
(ca fait deja beacoup de code mort 🐙 )

- https://github.com/For-Hives/ForVoyez/blob/de7d0dbd64c62c1912819667cb50fbbc5f2fdc6c/src/services/database.service.js#L214
- https://github.com/For-Hives/ForVoyez/blob/82730f5e7530f4b160174e99e2db19f3b06923b2/src/services/jwt.service.js#L47
- https://github.com/For-Hives/ForVoyez/blob/3824235a3ff1d5a0b43cf4e11ca5d365e54e2a94/src/services/lemonsqueezy.service.js#L39
-

**Comment by CinquinAndy** [comment]
j'ai delete toutes les functions marqués unused

**Comment by LightInn** [comment]
Dac, je ferais la review quand j'aurais un pc
