### ISSUE TITLE
Test e2e

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/ForVoyez#176]
- [ ] #204
- [x] #180
- [x] #181
- [x] #182
- [x] #183
- [x] #184
- [x] #185
- [x] #186
- [x] #187
- [x] #188
- [x] #189
- [x] #190
- [x] #191
- [x] #192
- [x] #193
- [x] #194
- [x] #195
- [x] #196
- [x] #197
- [x] #198
- [x] #199
- [x] #200
- [x] #201
- [x] #202
- [x] #203
- [x] #208
- [x] #209
- [x] #210
- [x] #211

**Comment by CinquinAndy** [comment]
@LightInn En vrai, de vrai, j'ai trop aucune idée de ce qu'on fait pour les test e2e, on refait du cypress like ? ou on en fait un autre ?

**Comment by CinquinAndy** [comment]
Soit on repart sur du cypress (qui en vrai, avait déjà bien fait le café) , soit on fait autre chose en vraiii idk

**Comment by LightInn** [comment]
Je testerais bien playwright

**Comment by CinquinAndy** [comment]
@LightInn Je sais pas trop trop comment je faire pour faire les tests des 
- #198 
- #199 
- #200 
- #201 
- #202 
- #204

**Comment by LightInn** [comment]
> @LightInn Je sais pas trop trop comment je faire pour faire les tests les; t'as une idée pour eviter de trop tester les parties payantes mais quand même les tester ? etc ? On teste quand même la suppression d'acc / sign up / paiment ? vu que c'est externalisé en soit, on est pas forcément obligé ?
> 
>     * [(test playwright) tester le subscribe & la bonne obtention des crédits #198](https://github.com/For-Hives/ForVoyez/issues/198)
> 
>     * [(test playwright) tester le changement de plan & la bonne obtention des crédits #199](https://github.com/For-Hives/ForVoyez/issues/199)
> 
>     * [(test playwright) tester l'achat de crédits unique & la bonne obtention des crédits #200](https://github.com/For-Hives/ForVoyez/issues/200)
> 
>     * [(test playwright) tester le playground avec des credits #201](https://github.com/For-Hives/ForVoyez/issues/201)
> 
>     * [(test playwright) tester l'usage avec des crédits #202](https://github.com/For-Hives/ForVoyez/issues/202)
> 
>     * [(test playwright) footer #204](https://github.com/For-Hives/ForVoyez/issues/204)

Je ne vois que deux possibilité : 
- On modifie le comportement des route payante quand on est en environement de tests pour avoir argent infini et skip juste la partie openia ( mais c'est un poile sale car on se retrouve a tester un environement qui n'est pas completement ISO )
- On ne fait pas de e2e pour ca, mais on blinde les tests unitaires sur ces parties
