### ISSUE TITLE
getCurrentUser export -> "mauvaise pratique d'export, ou erreur dans le front" 

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/ForVoyez#251]
cette methode n'a pas besoin d'etre exporter, c'est une mauvaise pratique d'exporter une methode priver juste pour ce faciliter la vie dans les tests

_Originally posted by @LightInn in https://github.com/For-Hives/ForVoyez/pull/224#discussion_r1631218203_

**Comment by CinquinAndy** [comment]
suite du commentaire que tu as mis & lié à : 
- #219

**Comment by CinquinAndy** [comment]
c'est ton code qui pète, je sais pas ce que tu voulais faire, mais pour ne pas avoir de bug sur le front (comme marqué dans la #219 ) , j'ai fait un export classique

Sauf que visiblement tu dis que ça te plais pas et que c'est une mauvaise pratique,
je ne sais pas comment tu veux faire autrement, je te laisse gérer

**Comment by LightInn** [comment]
Ah ok, j'ai peut être louper un truc, mybad 🤔  Je regarderais
