### ISSUE TITLE
db in local -> to handle concurrency potential issues

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/ForVoyez#252]
d'ailleur je pense que la meilleurs chose a faire pour la base de donnée, pour eviter des erreur de tests concurents, ce serais de la monter en local aussi (avec un docker composes genre) et de la peupler avec les donnée de tests grace au seed.js de prisma

_Originally posted by @LightInn in https://github.com/For-Hives/ForVoyez/pull/224#discussion_r1631322578_

**Comment by CinquinAndy** [comment]
en vrai de vrai, on a théoriquement aucune écriture dans la db, sauf pour le test de playground 
il devrait pas y avoir ce genre de soucis, 
Et on devrait brancher les tests à la db de prod quand on sera en prod, dans le sens où, il faut que les données de connexion pour avoir l'auth est lié à clerk, et il faut forcément les bons "clerkid" // "customerid" etc 

Donc de toute façon, si on veut faire des trucs en local, il faudrait avoir une copie de db de prod ou une partie de cette db du moins, ce qui peut potentiellement poser problème non ?

**Comment by LightInn** [comment]
ca me gene, on ne peux pas brancher les tests a une db de prods, ca na rien a faire la 
En plus les tests devienne dependant de de facteurs exterieurs dans ce cas la; ( si la db de prod est up, si neon est up, etc ) ce qui fait que on ne TEST pas a proprement parler que notre feature ou update 

Les tests devienne alors flacky par design et ca ne vas pas 



Je pense et j'espere que clerk a une solutions pour les env de staging / de tests, il faut checker

**Comment by LightInn** [comment]
Je suis aussi extreme car c'est un probleme recurents sur my makeup, je dois regulierement allez sur les tests pour les relancer car l'api preprod (donc exterieur au test) a fait foiré le tests, on ne peux alors plus faire confiance au tests et il perds tout son interet si on ne peut plus lui faire confiance 

Et pour les acces concurent, ce sera moins propice j'imagine vue la faible quantité d'ecriture, mais je sais que c'est un soucis regulier egalement sur my-makeup, et je dois regulierement allez remettre les données d'aplomb dans la db car un acces concurrent a essayer de lire des données alors qu'elles venaient de bouger

**Comment by LightInn** [comment]
ps: j'ai mal a mon francais, je ne sais pas ecrire c'est tres grave :'/

**Comment by CinquinAndy** [comment]
j'essaye de regarder si y'a pas moyen d'avoir un env de test, 
mais j'ia l'impression qu'on sera de toute façon obligé de compter sur l'api de clerk 

https://clerk.com/docs/testing/playwright

je suis en train de regarder pour faire en sorte de créer un utilisateur, récupérer son id en fonction de ce que clerk à décider de mettre, 
ajouter des crédits et tout pleins d'éléments fictifs, 
faire tout les tests, puis supprimer l'utilisateur

**Comment by LightInn** [comment]
> j'essaye de regarder si y'a pas moyen d'avoir un env de test, mais j'ia l'impression qu'on sera de toute façon obligé de compter sur l'api de clerk
> 
> https://clerk.com/docs/testing/playwright
> 
> je suis en train de regarder pour faire en sorte de créer un utilisateur, récupérer son id en fonction de ce que clerk à décider de mettre, ajouter des crédits et tout pleins d'éléments fictifs, faire tout les tests, puis supprimer l'utilisateur

Je suis tomber sur une page de clerk hier qui disait : 

"On ne supporte pas les env de staging pour le moment, MAIS tu peux creer une autre app clerk qui joue le role de l'env"
